export const SET_APP_INITIALIZED = 'SET_APP_INITIALIZED'

export const DISPLAY_MODAL = 'DISPLAY_MODAL'
export const HIDE_MODAL = 'HIDE_MODAL'
export const DISABLE_MODAL = 'DISABLE_MODAL'

export const SHOW_EVENTS_PRELOADER = 'SHOW_EVENTS_PRELOADER'
export const HIDE_EVENTS_PRELOADER = 'HIDE_EVENTS_PRELOADER'
export const SHOW_MODAL_PRELOADER = 'SHOW_MODAL_PRELOADER'
export const HIDE_MODAL_PRELOADER = 'HIDE_MODAL_PRELOADER'

export const SET_DOMAIN = 'SET_DOMAIN'
export const SET_THEME = 'SET_THEME'
export const SET_IS_SMALL_DESKTOP = 'SET_IS_SMALL_DESKTOP'
export const SET_IS_TOUCH_DEVICE = 'SET_IS_TOUCH_DEVICE'
export const SET_IS_MOBILE_PHONE = 'SET_IS_MOBILE_PHONE'
export const SET_IS_MEDIUM_MOBILE_PHONE = 'SET_IS_MEDIUM_MOBILE_PHONE'
